### ISSUE TITLE
Certificate of the API endpoint is over

### ISSUE THREAD

**Issue by Chartmastersorg** [evilarceus/Spotify-PlayCount#7]
Hi, 

The certificate of the endpoint https://t4ils.dev:4433/api/beta/albumPlayCount appears to be over.

Btw, I would be very glad to talk with you evilarceus about some projects. Get back to me if you can be interested.

Kind regards and keep up the great work

**Comment by ponzilover** [comment]
@evilarceus are you going to fix it?

**Comment by GCour** [comment]
Can you please take a look at this, my whole app is based on your API. @evilarceus

**Comment by ponzilover** [comment]
It works now
