### ISSUE TITLE
No messages sent from Spotify client to server

### ISSUE THREAD

**Issue by slapheadted** [evilarceus/Spotify-PlayCount#9]
## Environment

* macOS Mojave `10.14.5`
* Chrome `80.0.3987.87 (Official Build) (64-bit)`
* node `10.16.0`
* Mac Spotify Desktop App `1.1.26.501.gbe11e53b`

## Reproduction Steps

* Follow setup to modify `zlink.spa`, boot up `node` server, and launch Spotify Desktop app with relevant flags
* Verify the `node` process boots the server
* Verify the Spotify Desktop app connects to the server via websocket
* You should see the following:
```
$ node index.js 
http and ws server listening on port 8080!
o_> quack (client connected)
```
* At this point we are all good, set up is correct.
* Navigate to an album in Spotify Desktop app.
* Make request to server for playcounts for an album.

Actual behaviour: Request hangs...no response from server.
Expected behaviour: Response is sent from server (with playcounts).

## Solution
I fixed this locally by changing the variable `a` -> `i` in [this line](https://github.com/evilarceus/Spotify-PlayCount/blob/master/spotify_zlink.js#L7). I'm pretty sure that this would be a blocking issue for anyone, at least on Mac, and I strongly suspect Windows + Linux too (I can't see why a variable would be named differently between platforms).

It's difficult to tell by the long line but the change is this:

`a.default.resolver.get(uri,(e,t)=>{` -> `i.default.resolver.get(uri,(e,t)=>{`

~~Also, I'd open a PR but I don't think I have permissions to push a branch to this repo.~~ PR here https://github.com/evilarceus/Spotify-PlayCount/pull/10

## P.S.

How the hell do people debug the Spotify App? I see there are `console.log`s in this repo's code that could only be run on the Spotify App...how do you even see those? My understanding is that Dev Tools used to be available in previous versions of Spotify but that must be a long time ago.

**Comment by entriphy** [comment]
Closed by #10.

You can get access to Spotify's DevTools through [spicetify-cli](https://github.com/khanhas/spicetify-cli).
Then run the first two commands listed [here](https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage).
